name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      
      - name: Install dependencies
        run: npm install

      - name: Add node_modules/.bin to PATH
        run: echo "./node_modules/.bin" >> $GITHUB_PATH
      
      - name: Install Makecode PXT Arcade
        run: pxt target arcade

      - name: Build the project (Web)
        run: |
          pxt install
          pxt build --clean
          cp ./built/debug/binary.js binary.js

      - name: Build the project (D51)
        run: |
          pxt install --hw samd51
          pxt build --hw samd51 --clean
          cp ./built/binary.uf2 binary-d51.uf2

      - name: Build the project (F4)
        continue-on-error: true
        run: |
          pxt install --hw stm32f401
          pxt build --hw stm32f401 --clean
          cp ./built/binary.uf2 binary-f4.uf2

      - name: Build the project (P0)
        continue-on-error: true
        run: |
          pxt install --hw rpi
          pxt build --hw rpi --clean
          cp ./built/binary.uf2 binary-p0.uf2

      - name: DEBUG
        run: ls -la built

      - name: bundle all
        run: |
          cat binary-*.uf2 > assets/arcade.uf2
          cp binary.js assets/js/binary.js
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./assets
          name: github-pages

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment: github-pages

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
