name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [20.x]
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: npm install
      
      - name: Install Makecode PXT
        run: ./node_modules/.bin/pxt target arcade
        
      - name: Install PXT Dependencies
        run: ./node_modules/.bin/pxt install

      - name: Build the project (Web)
        run: ./node_modules/.bin/pxt build

      - name: DEBUG
        run: ls -la built
      
      - name: Move the built files to js folder
        run: mv built/debug/binary.js assets/js/binary.js

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./assets

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    environment: github-pages

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          artifact_name: github-pages
